/**
 * Regenerate src/lib/qc-boundary.ts from OSM (Quezon City, relation 106569,
 * admin_level 6 boundary) via Nominatim lookup. One request; run rarely.
 *
 *   node --experimental-strip-types scripts/fetch-boundary.ts
 *
 * Data © OpenStreetMap contributors, ODbL.
 */
import { writeFileSync } from "node:fs";

const REL = 106569;
const url = `https://nominatim.openstreetmap.org/lookup?osm_ids=R${REL}&format=jsonv2&polygon_geojson=1`;
const res = await fetch(url, { headers: { "User-Agent": "patas/0.1 (boundary fetch)" }, signal: AbortSignal.timeout(60_000) });
if (!res.ok) throw new Error(`Nominatim ${res.status}`);
const [hit] = (await res.json()) as Array<{ display_name: string; geojson: { type: string; coordinates: number[][][] } }>;
if (!hit || hit.geojson.type !== "Polygon" || hit.geojson.coordinates.length !== 1) {
  throw new Error(`expected a single-ring Polygon, got ${hit?.geojson.type}`);
}
const ring = hit.geojson.coordinates[0].map(([lng, lat]) => [+lng.toFixed(6), +lat.toFixed(6)]);

writeFileSync(
  "src/lib/qc-boundary.ts",
  `// GENERATED by scripts/fetch-boundary.ts on ${new Date().toISOString().slice(0, 10)} — do not edit.
// ${hit.display_name} (OSM relation ${REL}). Data © OpenStreetMap contributors, ODbL.
// Single outer ring, GeoJSON order [lng, lat], closed (first == last).
export const QC_OSM_RELATION = ${REL};
export const QC_RING: [number, number][] = ${JSON.stringify(ring)};
`,
);
console.log(`wrote src/lib/qc-boundary.ts (${ring.length} vertices)`);
